version: "3.8"

services:
  strm-sync-cleaner:
    build: .
    container_name: strm-sync-cleaner

    environment:
      - SCAN_INTERVAL=5   # 扫描间隔：86400 秒 = 24 小时

    volumes:
      # 导出未整理 STRM 的目录
      - /vol1/1000/happyemby/date/alist/同学数据:/raw

      # Emby 整理后的目录
      - /vol1/1000/happyemby/date/alist已整理/alist:/sorted

    restart: unless-stopped
