services:
  strm-sync-cleaner:
    build: .
    container_name: strm-sync-cleaner
    volumes:
      # 导出未整理 STRM 的目录
      - /vol3/1000/docker/AppData/strm:/raw
      # Emby 整理后的目录
      - /vol3/1000/lxcemby/emby/video:/sorted
    restart: unless-stopped

